apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-container
        image: anushavendra26/flask-monitoring-app:latest
        ports:
        - containerPort: 5050
        env:
        - name: APP_SECRET
          value: "ProductionSecret"
